### ISSUE TITLE
LineText params not working synchronously in Android and iOS

### ISSUE THREAD

**Issue by Musaddiq625** [thon-ju/bluetooth_print#94]
params:
> size
- Android :x:
- iOS :heavy_check_mark:

> weight
- Android :heavy_check_mark:
- iOS :x:

> width
- idk why the param is there, its not working

> x,y axis
- On same x-axis value in the list, It takes alignment value of last same value of x-axis param of the list

> image
- It doesnt have any option to set size of image

For now found these issues
I need to remove size and weight param from both Android and iOS sides code to make it work synchronously.

Although the package is so good
Ive used some other packages too, they dont have the support of iOS.

This package needs some update.

**Comment by Musaddiq625** [comment]
@xni06

**Comment by xni06** [comment]
Some of these issues may/should have been addressed in the PR's that have not yet been merged - see #77 #79 #80 #83. 

You can also try my fork that is the source of those PR's:

Use something like this in your `pubspec.yaml`

```
  bluetooth_print:
    git:
      url: https://github.com/foresightmobile/bluetooth_print.git
      ref: '44e3c58'
```
